### PR TITLE
New artists

### PR DESCRIPTION
**Pull request by Earlh21**
Adds 3 new artists: Jean Delville, Peter Mohrbacher, and Junji Ito.
Adds 2 new artist categories: Idealism and manga.

### CODE REVIEW

**Review by willwulfken — COMMENTED** [review]
Before I go ahead and approve this, I would just like to ask for the specific prompts you used.

**Comment by Earlh21** [comment]
"sphere, Painting by Jean Delville --seed 4776"
"sphere, Painting by Peter Mohrbacher --seed 4776"
"sphere, Art by Junji Ito --seed 4776"

**Comment by willwulfken** [comment]
Thank you! I just wanted to confirm.

**Comment by willwulfken** [comment]
Thank you so much for your contributions! I love that first image especially

**Pull request merged**
